### ISSUE TITLE
ReText unable to render .rst files in Windows10 due bug in restructuredtext.py (line 18)

### ISSUE THREAD

**Issue by Hrissimir** [retext-project/pymarkups#14]
The rendering fails due `AttributeError` on attempt to get `node.line` when `node` is `None`

The ReText issue is described [here](https://github.com/retext-project/retext/issues/560)

CMD stack below:

```
Exception occurred while parsing document:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\ReText\tab.py", line 249, in updatePreviewBox
    self.converted = self.converterProcess.get_result()
  File "C:\Program Files\Python39\lib\site-packages\ReText\converterprocess.py", line 184, in get_result
    raise ConversionError(result)
ReText.converterprocess.ConversionError: The background markup conversion process received this exception:
    Traceback (most recent call last):
      File "C:\Program Files\Python39\lib\site-packages\ReText\converterprocess.py", line 88, in _converter_process_func
        converted = current_markup.convert(job['text'])
      File "C:\Program Files\Python39\lib\site-packages\markups\restructuredtext.py", line 67, in convert
        parts = self._publish_parts(text, source_path=self.filename,
      File "C:\Program Files\Python39\lib\site-packages\docutils\core.py", line 441, in publish_parts
        output, pub = publish_programmatically(
      File "C:\Program Files\Python39\lib\site-packages\docutils\core.py", line 665, in publish_programmatically
        output = pub.publish(enable_exit_status=enable_exit_status)
      File "C:\Program Files\Python39\lib\site-packages\docutils\core.py", line 220, in publish
        output = self.writer.write(self.document, self.destination)
      File "C:\Program Files\Python39\lib\site-packages\docutils\writers\__init__.py", line 78, in write
        self.translate()
      File "C:\Program Files\Python39\lib\site-packages\docutils\writers\_html_base.py", line 80, in translate
        self.document.walkabout(visitor)
      File "C:\Program Files\Python39\lib\site-packages\docutils\nodes.py", line 227, in walkabout
        if child.walkabout(visitor):
      File "C:\Program Files\Python39\lib\site-packages\docutils\nodes.py", line 227, in walkabout
        if child.walkabout(visitor):
      File "C:\Program Files\Python39\lib\site-packages\docutils\nodes.py", line 219, in walkabout
        visitor.dispatch_visit(self)
      File "C:\Program Files\Python39\lib\site-packages\docutils\nodes.py", line 2021, in dispatch_visit
        return method(node)
      File "C:\Program Files\Python39\lib\site-packages\docutils\writers\_html_base.py", line 1572, in visit_title
        self.body.append(self.starttag({}, 'a', '', **atts))
      File "C:\Program Files\Python39\lib\site-packages\markups\restructuredtext.py", line 18, in starttag
        if node.line is not None:
    AttributeError: 'dict' object has no attribute 'line'

QEventDispatcherWin32::wakeUp: Failed to post a message (Invalid window handle.)
```

**Comment by mitya57** [comment]
Thank you for the bug report and for proposed PR. I will merge it, but I also want to write an automated test, so I have two questions:

- Does it happen with any reStructuredText file, including empty one, or only with some specific file?
- What is your docutils version? (e.g. `pip show docutils`).

**Comment by Hrissimir** [comment]
You're welcome!

* It happens with any .rst file, and I was unable to `View HTML code` even for empty files
* Output from `pip show docutils` below:

```
Name: docutils
Version: 0.17.1
Summary: Docutils -- Python Documentation Utilities
Home-page: http://docutils.sourceforge.net/
Author: David Goodger
Author-email: goodger@python.org
License: public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt)
Location: c:\program files\python39\lib\site-packages
Requires:
Required-by: Sphinx, ReText, recommonmark, readme-renderer
```
