### ISSUE TITLE
Tests fail on Fedora Linux with Python 3.10

### ISSUE THREAD

**Issue by jose-matos** [retext-project/pymarkups#18]
While building for Fedora Linux I got a failure in the test stage:

https://kojipkgs.fedoraproject.org//work/tasks/4319/81114319/build.log

Specifically the problem happens in the yaml section:

```
======================================================================
FAIL: test_extensions_yaml_file (tests.test_markdown.MarkdownTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Markups-3.1.3/tests/test_markdown.py", line 314, in test_extensions_yaml_file
    self.assertEqual(
AssertionError: Lists differ: [] != [('smarty', {'substitutions': {'left-singl[158 chars] {})]
Second list contains 3 additional elements.
First extra element 0:
('smarty', {'substitutions': {'left-single-quote': '&sbquo;', 'right-single-quote': '&lsquo;'}, 'smart_dashes': False})
- []
+ [('smarty',
+   {'smart_dashes': False,
+    'substitutions': {'left-single-quote': '&sbquo;',
+                      'right-single-quote': '&lsquo;'}}),
+  ('toc', {'permalink': True, 'separator': '_', 'toc_depth': 3}),
+  ('sane_lists', {})]
======================================================================
FAIL: test_extensions_yaml_file_invalid (tests.test_markdown.MarkdownTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Markups-3.1.3/tests/test_markdown.py", line 331, in test_extensions_yaml_file_invalid
    with self.assertWarns(SyntaxWarning) as cm:
AssertionError: SyntaxWarning not triggered
----------------------------------------------------------------------
```

Any help on this?

**Comment by mitya57** [comment]
Please make sure you have PyYAML installed.

I probably should make these tests skipped when it's not installed.

**Comment by jose-matos** [comment]
That makes sense. Thank you for the quick answer. :-)

Should not this and other packages be referred as dependencies in `setup.cfg` or in `pyproject.toml`?

**Comment by mitya57** [comment]
> Should not this and other packages be referred as dependencies in `setup.cfg` or in `pyproject.toml`?

It is listed there:
https://github.com/retext-project/pymarkups/blob/363181ba2f81127b37d5582e2e33b44cc73d9f4e/setup.cfg#L36
